### ISSUE TITLE
k-Wave fails to select a device

### ISSUE THREAD

**Issue by thorstone25** [waltsims/k-wave-python#11]
k-Wave fails to select a device and outputs no data on my system.

```
Setting up the k-wave grid...
Defining the input signal...
Setting up the transducer configuration...
Fetching phantom data...
RUN_SIMULATION set to True
Running simulation locally...
Computing scan line 1 of 96
/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/kwave/kspaceFirstOrder.py:99: UserWarning: 
                    The binary file kspaceFirstOrder-OMP could not be found in None. 
                    To use the C++ code, the C++ binaries for your operating system must be downloaded 
                    from www.k-wave.org/download.php and placed in the binaries folder.
  warn(f'''
  start time: 04-May-2022-13-11-33
Running k-Wave simulation...
  start time: 04-May-2022-13-11-33
  reference sound speed:  1600.7033686418115 m/s
  reference sound speed:  1600.7033686418115 m/s
  prepending transducer.input_signal with 17 leading zeros
  appending transducer.input_signal with 17 trailing zeros
  dt:  36.075ns , t_end: 57.1429us , time steps: 1585
  input grid size: 216 by 108 by 108 grid points (40.0 by 20.0 by 20.0 m)
  maximum supported frequency:  3.78MHz
  expanding computational grid...
  computational grid size: 256 by 128 by 128 grid points
  precomputation completed in  3.8572562130284496 s
  saving input files to disk...
  completed in  0.3157105499994941 s
┌───────────────────────────────────────────────────────────────┐
│                  kspaceFirstOrder-CUDA v1.3                   │
├───────────────────────────────────────────────────────────────┤
│ Reading simulation configuration:                        Done │
│ Selected GPU device id:                                Failed │
└───────────────────────────────────────────────────────────────┘
┌───────────────────────────────────────────────────────────────┐
│            !!! K-Wave experienced a fatal error !!!           │
├───────────────────────────────────────────────────────────────┤
│ Error: All CUDA-capable devices are busy or unavailable.      │
├───────────────────────────────────────────────────────────────┤
│                      Execution terminated                     │
└───────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "examples/bmode_reconstruction_example.py", line 174, in <module>
    sensor_data = kspaceFirstOrder3DC(**{
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/kwave/kspaceFirstOrder.py", line 283, in wrapper
    res = func(kgrid=kgrid, medium=medium, source=source, sensor=sensor, **args, **kwargs)
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/kwave/kspaceFirstOrder3D.py", line 92, in kspaceFirstOrder3DC
    sensor_data = kspaceFirstOrder3D(**kwargs)
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/kwave/kspaceFirstOrder3D.py", line 412, in kspaceFirstOrder3D
    sensor_data = executor.run_simulation(input_filename, output_filename, options='--p_raw')
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/kwave/executor.py", line 55, in run_simulation
    with h5py.File(output_filename, 'r') as hf:
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/media/thurston/home/thurston/Projects/k-wave-python/venv_debug/lib/python3.8/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/tmp/output.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

```

**Comment by waltsims** [comment]
This looks like an error in your local CUDA setup. perhaps restart you computer and try again? 

One thing I notice is that erroneous warning above. That needs to be addressed.

**Comment by thorstone25** [comment]
CUDA seems to work for me in other programs. I tried on two computers, each running ampere cards on nvidia-driver-510.47.03. On each it hung for about a minute first and then failed. Subsequent runs it fails immediately. I suspect it's an architecture issue with compiled binares for ampere?

**Comment by waltsims** [comment]
That is likely. The pre-compiled binaries are shipped with this package, which are only compiled for sm 3.0-7.5.

<img width="582" alt="Screenshot 2022-05-04 at 13 46 45" src="https://user-images.githubusercontent.com/8669206/166823168-5d28cb6e-ff1c-4351-9874-66de1f1d60a8.png">

Perhaps we will have a new build strategy in future releases and compile from source. Closing for now. Please re-open if you experience the same issues on an sm between 3.0 and 7.5.
