### ISSUE TITLE
Example Bmode reconstruction doesn't run

### ISSUE THREAD

**Issue by kwsp** [waltsims/k-wave-python#16]
Trying to run the example but getting a type error in the `uff` dependency.

Using the latest version of k-wave-python from github on Ubuntu (WSL2).

```
(sim) ~ python3 bmode_reconstruction_example.py
Traceback (most recent call last):
  File "/home/tnie/code/sim/k-wave-python/examples/bmode_reconstruction_example.py", line 4, in <module>
    from kwave.reconstruction.beamform import beamform
  File "/home/tnie/code/sim/k-wave-python/kwave/reconstruction/beamform.py", line 4, in <module>
    from uff import UFF, ChannelData
  File "/home/tnie/miniconda3/envs/sim/lib/python3.10/site-packages/uff/__init__.py", line 48, in <module>
    from uff import converters, model  # noqa
  File "/home/tnie/miniconda3/envs/sim/lib/python3.10/site-packages/uff/model/__init__.py", line 48, in <module>
    from . import uff_pb2 as uff_pb  # noqa
  File "/home/tnie/miniconda3/envs/sim/lib/python3.10/site-packages/uff/model/uff_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/tnie/miniconda3/envs/sim/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by waltsims** [comment]
Thank you for this, I'll look into it!

**Comment by waltsims** [comment]
Can you share with me the output of ```pip freeze```?

**Comment by kwsp** [comment]
```
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
cycler==0.11.0
fonttools==4.33.3
h5py==3.7.0
-e git+ssh://git@github.com/kwsp/k-wave-python.git@1147462c92c112f3c1ec85e3427adbd020bb16e1#egg=k_Wave_python
kiwisolver==1.4.3
matplotlib==3.5.2
numpy==1.23.0
nvidia-pyindex==1.0.9
opencv-python==4.6.0.66
packaging==21.3
Pillow==9.2.0
protobuf==4.21.2
pyparsing==3.0.9
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
python-dateutil==2.8.2
scipy==1.8.1
six==1.16.0
uff==0.6.9
```

**Comment by waltsims** [comment]
It looks like you have installed another package called uff. Currently uff.py, the python port of the ultrasound file format, is not published to PyPi. There is another package called [uff](https://pypi.org/project/uff/) from NVIDIA with (currently) the same package name.

things should work if you uninstall uff with

```pip install pypi```
and install uff.py as defined in the requirement files via

```
pip install git+https://github.com/waltsims/uff.py@a672319b5cfbe3a676837e47c5958a3fdea12fa7
```

Please let me know if that works for you.

**Comment by waltsims** [comment]
There was a typo in the uninstall command that I just corrected.

**Comment by waltsims** [comment]
After testing the solution this should solve your issue. closing for now.
