### ISSUE TITLE
[BUG] AttributeError: 'kWaveSimulation' object has no attribute 'record_u_split_field'

### ISSUE THREAD

**Issue by shahwaiz-git** [waltsims/k-wave-python#238]
hello
when i wanna to imply my matlab simulation to the kwave-python, i get the following error:
```
WARNING:root:Highest prime factors in each dimension are [23 23]
WARNING:root:Use dimension sizes with lower prime factors to improve speed
Traceback (most recent call last):
  File "D:\HISLab\毕设\CODE\DATA\mydataset.py", line 76, in <module>
    sensor_data = kspace_first_order_2d_gpu(
  File "D:\HISLab\MODEL\Github\k-wave-python-master\kwave\kspaceFirstOrder2D.py", line 64, in kspace_first_order_2d_gpu
    sensor_data = kspaceFirstOrder2DC(
  File "D:\HISLab\MODEL\Github\k-wave-python-master\kwave\kspaceFirstOrder2D.py", line 132, in kspaceFirstOrder2DC
    sensor_data = kspaceFirstOrder2D(
  File "D:\HISLab\MODEL\Github\k-wave-python-master\kwave\kspaceFirstOrder2D.py", line 305, in kspaceFirstOrder2D
    k_sim.input_checking('kspaceFirstOrder2D')
  File "D:\HISLab\MODEL\Github\k-wave-python-master\kwave\kWaveSimulation.py", line 515, in input_checking
    self.create_sensor_variables()
  File "D:\HISLab\MODEL\Github\k-wave-python-master\kwave\kWaveSimulation.py", line 1381, in create_sensor_variables
    'record_u_split_field': self.record_u_split_field,
AttributeError: 'kWaveSimulation' object has no attribute 'record_u_split_field'
```

this is my simulation code in python,  i do the same step like kwave in matlab
```
import mat73
import scipy
import numpy as np
from kwave.data import Vector
from kwave.kgrid import kWaveGrid
from kwave.kmedium import kWaveMedium
from kwave.ksensor import kSensor
from kwave.ksource import kSource
from kwave.kspaceFirstOrder2D import kspace_first_order_2d_gpu
from kwave.options.simulation_execution_options import SimulationExecutionOptions
from kwave.options.simulation_options import SimulationOptions
from kwave.utils.conversion import cart2grid
from kwave.utils.kwave_array import kWaveArray
from kwave.utils.mapgen import make_cart_circle, make_disc
from kwave.utils.signals import reorder_binary_sensor_data

phantom_path = '../phantom.mat'
density_map_path = '../density_map.mat'
phantom = mat73.loadmat(phantom_path)['phantom']
density_map = mat73.loadmat(density_map_path)['density_map']



# grid
PMLSize = Vector([20, 20])
grid_dsize = Vector([1e-4, 1e-4])
grid_pixel = Vector([512, 512])
kgrid = kWaveGrid(grid_pixel, grid_dsize)

# medium
medium = kWaveMedium(
    sound_speed=1.5*density_map,
    density=density_map,
    alpha_coeff=0.75,
    alpha_power=1.5,
    BonA=6
)
kgrid.makeTime(medium.sound_speed)

# sensor
sensor = kSensor()
sensor_mask = np.zeros(grid_pixel)
sensor_radius = 200
sensor_angle = 2*np.pi
sensor_pos = grid_dsize / 2
sensor_points = 100
sensor_mask_idx = make_cart_circle(
    radius=sensor_radius,
    num_points=sensor_points,
    arc_angle=sensor_angle,
).astype(np.int16)
for x, y in sensor_mask_idx.T:
    sensor_mask[x, y] = 1
sensor.mask = sensor_mask

# source
source = kSource()
x = 250
y = 300
source_radius = 5
disc = make_disc(
    grid_size=grid_pixel,
    center=Vector([x, y]),
    radius=source_radius
)

source.p0 = phantom + disc

# simulation
simulation_options = SimulationOptions(
    pml_size=PMLSize,
    pml_inside=False,
)
execution_options = SimulationExecutionOptions(is_gpu_simulation=True)

sensor_data = kspace_first_order_2d_gpu(
    kgrid=kgrid,
    source=source,
    sensor=sensor,
    medium=medium,
    simulation_options=simulation_options,
    execution_options=execution_options)
```
thanks

**Comment by waltsims** [comment]
Hey [shahwaiz](https://github.com/shahwaiz-git),

I was able to reproduce your error. Please update your simulation options to include the save to disk option set to true. It should look something like this:

```python3
simulation_options = SimulationOptions(
    pml_size=PMLSize,
    pml_inside=False,
    save_to_disk=True
)
```

With this change, your simulation should run.

We should update our error messages to make this clearer. Thanks!

Best,
Walter
