### ISSUE TITLE
[BUG]str'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)

### ISSUE THREAD

**Issue by lxy-zjn** [waltsims/k-wave-python#488]
str'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)
'''
try:
    output = kspaceFirstOrder2D(k_grid, source, sensor, medium, simulation_options, execution_options)
except Exception as e:
    print(f"仿真过程中出现错误: str{e}")
'''

**Comment by lxy-zjn** [comment]
this is my code

import os  # 导入操作系统相关模块
import numpy as np  # 导入 NumPy，用于数值计算
import matplotlib.pyplot as plt  # 导入 Matplotlib，用于数据可视化
from kwave.kgrid import kWaveGrid  # 从 k-wave 导入 kWaveGrid 类，用于创建网格
from kwave.kmedium import kWaveMedium  # 从 k-wave 导入 kWaveMedium 类，用于定义介质
from kwave.ksource import kSource  # 从 k-wave 导入 kSource 类，用于定义声源
from kwave.ksensor import kSensor  # 从 k-wave 导入 kSensor 类，用于定义传感器
from kwave.kspaceFirstOrder2D import kspaceFirstOrder2D  # 导入 2D 有限差分时域仿真函数
from kwave.options.simulation_options import SimulationOptions  # 导入仿真选项类
from kwave.options.simulation_execution_options import SimulationExecutionOptions  # 导入执行选项类
import tempfile  # 导入临时文件相关模块
import sys  # 导入系统模块
import io  # 导入输入输出模块

# 设置标准输出编码为 UTF-8，以支持非 ASCII 字符
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 准备网格
grid_size = (256, 256)  # 网格大小为 256x256
spacing = (0.1, 0.1)  # 网格间距为 0.1
k_grid = kWaveGrid(grid_size, spacing)  # 创建 kWaveGrid 对象

# 定义介质
medium = kWaveMedium(sound_speed=1500)  # 创建介质，声速为 1500 m/s

# 创建源
source = kSource()  # 创建声源对象
initial_pressure = np.zeros((k_grid.Nx, k_grid.Ny))  # 初始化声源压力为 0
initial_pressure[128, 128] = 1  # 在网格中心位置设置初始压力为 1
source.p0 = initial_pressure.astype('U1')  # 将初始压力强制转换为 UTF-8 字符串类型

# 创建传感器
sensor = kSensor()  # 创建传感器对象
num_sensors = 64  # 定义传感器数量
sensor_mask = np.zeros(grid_size, dtype=bool)  # 初始化传感器掩码
sensor_positions = np.linspace(0, grid_size[0] - 1, num_sensors).astype(int)  # 生成传感器位置
for pos in sensor_positions:  # 遍历传感器位置
    sensor_mask[pos, :] = True  # 在传感器位置设置掩码为 True
sensor.mask = sensor_mask.astype('U1')  # 将掩码转换为 UTF-8 字符串类型

# 打印调试信息
print("声源数据类型:", type(source.p0))  # 打印声源数据类型
print("声源数据形状:", source.p0.shape)  # 打印声源数据形状
print("k_grid:", k_grid)  # 打印网格信息
print("source.p0:", source.p0)  # 打印声源初始压力
print("sensor.mask:", sensor.mask)  # 打印传感器掩码
print("medium:", medium)  # 打印介质信息

# 定义仿真选项
temp_dir = 'D:\\k_wave_simulate\\temp'  # 设置临时目录
input_filename = 'D:\\k_wave_simulate\\temp\\input_file.h5'  # 设置输入文件名，确保使用字符串格式
print(f"临时目录: {temp_dir}")  # 打印临时目录
print(f"输入文件名: {input_filename}")  # 打印输入文件名

# 创建仿真选项对象
simulation_options = SimulationOptions(save_to_disk=True, input_filename=input_filename)  # 定义仿真选项
execution_options = SimulationExecutionOptions(is_gpu_simulation=True)  # 定义执行选项，启用 GPU 仿真

# 执行仿真并捕获异常
try:
    result = kspaceFirstOrder2D(k_grid, source, sensor, medium, simulation_options, execution_options)  # 执行仿真
except Exception as e:  # 捕获异常
    print(f"仿真过程中出现错误: {str(e)}")  # 打印错误信息

# 可视化结果
if 'result' in locals():  # 检查结果是否存在
    plt.imshow(result["p"], aspect='auto', cmap='hot')  # 绘制压力场
    plt.colorbar(label='Pressure (Pa)')  # 添加色条
    plt.title('Pressure Field')  # 设置标题
    plt.xlabel('X Position')  # 设置 X 轴标签
    plt.ylabel('Y Position')  # 设置 Y 轴标签
    plt.show()  # 显示图像

**Comment by lxy-zjn** [comment]
Traceback (most recent call last):
  File "D:\k_wave_simulate\test_encoding.py", line 154, in <module>
    result = kspaceFirstOrder2D(k_grid, source, sensor, medium, simulation_options, execution_options)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\kspaceFirstOrder2D.py", line 387, in kspaceFirstOrder2D
    save_to_disk_func(
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\kWaveSimulation_helper\save_to_disk_func.py", line 66, in save_to_disk_func
    save_file(opt.input_filename, integer_variables, float_variables, opt.hdf_compression_level, auto_chunk=auto_chunk)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\kWaveSimulation_helper\save_to_disk_func.py", line 470, in save_file
    save_h5_file(filepath, integer_variables, float_variables, hdf_compression_level, auto_chunk)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\kWaveSimulation_helper\save_to_disk_func.py", line 506, in save_h5_file
    write_attributes(filepath)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\utils\io.py", line 242, in write_attributes
    assign_str_attr(f.attrs, key, value)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\kwave\utils\io.py", line 478, in assign_str_attr
    attrs.create(attr_name, attr_val, None, dtype=f"<S{len(attr_val)}")
  File "D:\anaconda3\envs\ksmu\lib\site-packages\h5py\_hl\attrs.py", line 131, in create
    data = base.array_for_new_object(data, specified_dtype=dtype)
  File "D:\anaconda3\envs\ksmu\lib\site-packages\h5py\_hl\base.py", line 118, in array_for_new_object
    data = np.asarray(data, order="C", dtype=as_dtype)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)
